// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Incident struct {
	ID              uuid.UUID
	WebsiteID       uuid.UUID
	StartedAt       time.Time
	EndedAt         sql.NullTime
	DurationSeconds sql.NullInt32
	Cause           string
}

type PerformanceReport struct {
	ID             int64
	WebsiteID      uuid.UUID
	CheckedAt      time.Time
	TtfbMs         sql.NullInt32
	LcpMs          sql.NullInt32
	FullLoadTimeMs sql.NullInt32
	PageSizeKb     sql.NullInt32
}

type Plan struct {
	ID                    int32
	Name                  string
	PriceMonthly          string
	MaxWebsites           int32
	CheckIntervalSeconds  int32
	HasPerformanceReports bool
	HasSeoAudits          bool
	HasPublicStatusPage   bool
}

type SeoAudit struct {
	ID        int64
	WebsiteID uuid.UUID
	AuditedAt time.Time
	Results   json.RawMessage
}

type Subscription struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	PlanID               int32
	Status               string
	StripeSubscriptionID sql.NullString
	CurrentPeriodEndsAt  sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type UptimeCheck struct {
	ID             int32
	WebsiteID      uuid.UUID
	CheckedAt      time.Time
	IsUp           bool
	ResponseTimeMs int32
	StatusCode     int32
	ErrorMessage   sql.NullString
}

type User struct {
	ID              uuid.UUID
	Name            string
	Email           string
	PasswordHash    string
	EmailVerifiedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Website struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	Name                 string
	Url                  string
	IsActive             bool
	CheckIntervalSeconds int32
	LastCheckedAt        sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
